Resources:
  S3FullAccessPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - s3-object-lambda:*
            Resource: "*"

  MyIAMRole401:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyS3Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref S3FullAccessPolicy

  MyIamBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: iambucket101
  MyIamBucket2:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: iambucket201

Outputs:
  myrole101:
    Value: !GetAtt MyIAMRole401.Arn
# aws cloudformation validate-template --template-body file://IAM_ROLE_3.1.1.yaml
# aws cloudformation create-change-set --stack-name myrole101 --change-set-name first-change-set101 --change-set-type UPDATE --template-body file://IAM_ROLE_3.1.2_custompolicy.yaml --capabilities CAPABILITY_NAMED_IAM
# aws cloudformation create-stack --stack-name myrole101 --template-body file://IAM_ROLE_3.1.1.yaml --capabilities CAPABILITY_NAMED_IAM

#list roles - aws iam list-roles
#get role - aws iam get-role --role-name MyRole
#aws cloudformation describe-stacks --stack-name myrole101

#aws iam simulate-principal-policy --policy-source-arn arn:aws:iam::YOUR_ACCOUNT_ID:role/Role1 --action-names "iam:CreateRole" "iam:ListRoles" "iam:SimulatePrincipalPolicy" "ec2:DescribeImages" "ec2:RunInstances" "ec2:DescribeSecurityGroups"
#aws cloudformation create-stack --stack-name TrustPolicy --template-body file://TrustPolicy_3.2.1.yaml --capabilities CAPABILITY_NAMED_IAM